### ISSUE TITLE
Address space overlapping?

### ISSUE THREAD

**Issue by mattbettcher** [zeta0134/rusticnes-core#1]
I love your NES emulator, great effort!

I noticed you added MMC3 mapper so I immediately tried out SMB3 and it seemed to work perfectly ... at first. After a min or so of play it gets corrupted. I myself am writing a NES emulator to learn Rust and had a look at your code to compare to my implementation and noticed you don't separate your read/write calls by chr/prg. I think that could be where the corruption is coming from. Data is 'leaking' across to the chr address space. Top game is Contra Force, it starts out fine then after a minute or so it corrupts. Same thing with SMB3. In other emulators (higan, sprocketnes, bizhawk) prg and chr are separate. Let me know what you think.

![untitled](https://user-images.githubusercontent.com/1308317/31644016-b7dcdd44-b2c1-11e7-90ab-7eef8b0084b7.png)
![untitled2](https://user-images.githubusercontent.com/1308317/31644078-225445fe-b2c2-11e7-96ac-2e5bf5ec0a61.png)

**Comment by zeta0134** [comment]
You may be on to something there. I know there's at least one major bug though: if the VRAM debugger is open, the reads that *it* makes affect the MMC3 state, and they definitely should not. I have memory reads working with a side_effects flag, and I suspect the mapper and PPU reads will need something similar. I noticed that games easily get corrupted due to missed IRQ timings with the debug window open.

I'll check into the CHR / PRG split. My running mental model is that the address space of the read should be enough to differentiate the two (CHR in 0x0000 ... 0x1000, PRG in 0x6000 ... 0xFFFF) and that's how my IRQ counting presently works, but it's obviously bugged and that may not be a valid assumption.

**Comment by zeta0134** [comment]
This is finally fixed by baca9a2ae62d8c7488383b992687be3d0f35657d. I was able to validate that CHR reads are definitely designated by being within 0x1FFF, the problem was a poor interaction with tile fetches and invalid sprites, which explained why the manifestation seemed so random.

Essentially, any time there were no sprites on a line, there was a good chance that the fetches performed for dummy sprites would have Y offsets that greatly exceeded the usual 0-15 range, and I wasn't clamping the resulting address. I'm not sure how a real NES performs these fetches, but I was able to correct the reads from MMC3's point of view by ensuring that the fetch address was always within the chosen pattern table, even for weird Y offsets. I'd like to nail this down properly, I know a real NES would set the Y position to 0xFF for inactive sprites, but I'm not sure how it calculates the Y offset after that based on the current scanline.

In any case, thanks for the report! Mario 3 and Kirby Adventure are both working properly for the first time, and I fixed a bunch of little memory timing bugs in the process of debugging this one.

**Comment by mattbettcher** [comment]
Very nice, good to hear.
